package constant

var FileName = map[string]string{
	"会话相关": "conversationManagement",
	"好友管理": "friendsManagement",
	"群组管理": "groupManagement",
	"用户管理": "userManagement",

	"消息相关":     "messageManagement",
	"三方服务":     "thirdManagement",
	"撤回消息":     "revokeMessage",
	"删除用户所有消息": "deleteUserAllMessage",
	"发送消息":     "sendMessage",
	"批量发送消息":   "batchSendMessage",

	"导入用户": "userRegister",
	"修改指定用户全局免打扰状态":   "updateGlobalRemind",
	"获取指定用户详情列表":      "getSpecifiedUser",
	"获取管理员token":      "getToken",
	"获取用户token":       "getUserToken",
	"查询用户是否注册":        "checkUserRegistered",
	"获取已注册用户列表":       "getUserList",
	"获取已注册用户ID列表":     "getUserIDList",
	"修改用户信息":          "updateUserInfo",
	"获取指定用户在线状态":      "getUserOnlineStatus",
	"获取指定用户在线token详情": "getUserOnlineTokenDetail",

	"获取指定用户所订阅用户的在线状态": "getSubscribeUsersStatus",
	"修改用户的在线状态订阅关系":    "subscribeUsersStatus",
	"统计用户注册":           "statisticsUserRegister",

	"检查好友关系":    "checkFriend",
	"获取收到的好友申请": "getRecvApplication",
	"移除黑名单":     "deleteBlackList",
	"获取好友列表":    "getFriendList",
	"修改好友备注":    "setFriendRemark",
	"发起好友申请":    "sendApplication",
	"删除好友":      "deleteFriend",
	"获取黑名单列表":   "getBlackList",
	"添加黑名单":     "addBlackList",
	"导入好友":      "importFriend",
	"处理好友申请":    "processApplication",
	"获取发起的好友申请": "getSentApplication",

	"多个用户对同一会话设置字段": "setConversations",
	"获取当前用户的分页会话列表": "getOwnerConversation",

	"创建群组":        "createGroup",
	"邀请进群":        "inviteUserToGroup",
	"申请入群":        "joinGroup",
	"退出群组":        "quitGroup",
	"转让群主":        "transferGroup",
	"获取群组信息":      "getGroupsInfo",
	"移除群成员":       "kickGroup",
	"获取指定群成员":     "getGroupMembersInfo",
	"获取群成员列表":     "getGroupMemberList",
	"获取已加入群组":     "getJoinedGroupList",
	"修改群成员信息":     "setGroupMemberInfo",
	"禁言群组":        "muteGroup",
	"取消群禁言":       "cancelMuteGroup",
	"解散群":         "dismissGroup",
	"禁言群成员":       "muteGroupMember",
	"取消禁言群成员":     "cancelMuteGroupMember",
	"修改群组信息":      "setGroupInfo",
	"获取收到的入群申请":   "getRecvGroupApplicationList",
	"处理入群申请":      "groupApplicationResponse",
	"获取发起的入群申请":   "getUserReqGroupApplicationList",
	"获取指定用户的入群申请": "getGroupApplicationListByUserID",

	"强制下线": "forceLogout",
}

var Exclude = map[string]struct{}{
	"获取最新seq":                   {},
	"通过seq拉取消息":                 {},
	"用户清空指定会话ID消息":              {},
	"用户删除会话指定消息":                {},
	"按时间物理删除消息":                 {},
	"按seq物理删除消息":                {},
	"获取会话最大seq和用户已读最大seq":       {},
	"标记seq列表中消息已读并且发送已读回执同步未读数": {},
	"SDK-Core编译文档":              {},
	"OpenIM文档撰写说明以及参数":          {},
	"消息类型格式描述":                  {},
	"获取用户所有会话":                  {},
	"批量设置会话字段":                  {},
	"用户根据会话ID获取指定会话":            {},
	"用户根据会话ID获取单个会话":            {},
	"设置会话免打扰":                   {},
	"调整会话字段":                    {},
	"获取群成员哈希":                   {},
	"OpenIM字段说明":                {},
	"普通用户获取用户在线状态":              {},
	"获取指定好友双向申请列表":              {},
	"获取指定好友信息":                  {},
	"获取增量会话列表":                  {},
	"获取全量会话ID列表":                {},
	"获取特定好友列表":                  {},
	"获取好友ID列表":                  {},
	"获取全量好友ID列表":                {},
	"获取增量好友列表":                  {},
	"获取全量群成员ID列表":               {},
	"获取全量已加入群组ID列表":             {},
	"获取增量群成员列表":                 {},
	"批量获取增量群成员列表":               {},
	"获取增量已加入群组列表":               {},
	"批量发送消息":                    {},
	"查询消息":                      {},
	"获取群成员用户ID列表":               {},
	"修改用户信息old":                 {},
	"修改群组信息old":                 {},
}
